### ISSUE TITLE
SyntaxError: invalid syntax while loading plugin

### ISSUE THREAD

**Issue by albertz** [SublimeText/Modelines#7]
```
reloading plugin SublimeModelines.sublime_modelines
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_modelines in /Users/az/Library/Application Support/Sublime Text 3/Installed Packages/SublimeModelines.sublime-package", line 110
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

**Comment by albertz** [comment]
I think #6 fixes this. I tried, however, I'm unable to come up with a valid modeline to use Python syntax. I'm trying this:

    # sublime: syntax Packages/Python/Python.sublime-syntax

But it does not work. I always get the error:

    [SublimeModelines] Packages/Python/Python.sublime-syntax cannot be resolved to a syntaxfile
